/************************************************************* 
 * 
 * Ice Hockey Manager 
 * ================== 
 * 
 * Copyright (C) by the IHM Team (see doc/credits.txt) 
 * 
 * This program is released under the GPL (see doc/gpl.txt) 
 * 
 * Further informations: http://www.icehockeymanager.org  
 * 
 *************************************************************/ 
  
package org.icehockeymanager.ihm.game.training.log;

import java.util.*;
import java.util.logging.*;

import org.icehockeymanager.ihm.game.eventlog.*;
import org.icehockeymanager.ihm.game.team.*;
import org.icehockeymanager.ihm.game.training.*;
import org.icehockeymanager.ihm.lib.*;

/**
 * TrainingEventLog logs a Trainingschedule of a teams training.
 * 
 * @author Bernhard von Gunten
 * @created September, 2004
 */
public class TrainingEventLog extends EventLogEntry implements IhmLogging {

  /**
   * Comment for <code>serialVersionUID</code>
   */
  private static final long serialVersionUID = 3258128068156667443L;

  /**
   * MESSAGE_KEY
   */
  public static final String MESSAGE_KEY = "events.trainingschedulecreated";

  /**
   * TrainingSchedule
   */
  private TrainingSchedule schedule = null;

  /**
   * Auto training flag
   */
  private boolean auto = false;

  /**
   * TrainingEventLog constructor
   * 
   * @param source
   * @param day
   * @param team
   * @param schedule
   * @param auto
   */
  public TrainingEventLog(Object source, Calendar day, Team team, TrainingSchedule schedule, boolean auto) {
    super(source, day, team);
    try {
      this.schedule = (TrainingSchedule) schedule.clone();
      this.auto = auto;
    } catch (Exception err) {
      logger.log(Level.SEVERE, "clone failed!", err);
    }
  }

  /**
   * Returns TraingSchedule
   * 
   * @return schedule
   */
  public TrainingSchedule getSchedule() {
    return schedule;
  }

  /**
   * Retruns true if schedule was autogenerated.
   * 
   * @return true if schedule was autogenerated
   */
  public boolean isAuto() {
    return auto;
  }

}