/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __mechanics_BattleMechanics__
#define __mechanics_BattleMechanics__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jbyteArray JNICALL Java_mechanics_BattleMechanics_getRandomBytes (JNIEnv *env, jclass, jint);
#undef mechanics_BattleMechanics_serialVersionUID
#define mechanics_BattleMechanics_serialVersionUID 2907773868045621558LL

#ifdef __cplusplus
}
#endif

#endif /* __mechanics_BattleMechanics__ */
