/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __shoddybattleclient_FirstLaunch__
#define __shoddybattleclient_FirstLaunch__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jstring JNICALL Java_shoddybattleclient_FirstLaunch_getApplicationDataDirectory (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif

#endif /* __shoddybattleclient_FirstLaunch__ */
